// lib/payoutPartnerSign.js (client)
// Tanda tangan OWNER partner pada BAST: gambar tanda tangan (dan stempel opsional) partner
// ditempel HANYA di kolom PIHAK KEDUA (di atas nama OWNER / JABATAN), tidak pernah di kolom IOH.
// Hasilnya disimpan sebagai salinan baru (file asli — termasuk yang sudah approved — tidak diubah).
// Gambar tanda tangan disimpan di browser partner saja.
import supabase from './supabase';
import { DOCS_BUCKET } from './payoutPartnerDocs';

export const OWNER_SIG_KEY = 'ppd_owner_signature';     // terpisah dari pengaturan tanda tangan SPM
export const SIGNED_OWNER_SUFFIX = '_signed-owner';
export const readOwnerSig = () => { try { return JSON.parse(localStorage.getItem(OWNER_SIG_KEY) || 'null') || {}; } catch { return {}; } };
export const writeOwnerSig = (v) => { try { localStorage.setItem(OWNER_SIG_KEY, JSON.stringify(v)); return true; } catch { return false; } };
export const isOwnerSigned = (name) => String(name || '').includes(SIGNED_OWNER_SUFFIX);
export const ownerSignedName = (name) => String(name || 'BAST.pdf').replace(/(\.pdf)?$/i, `${SIGNED_OWNER_SUFFIX}.pdf`);

// Gambar → data URL kecil (PNG tetap PNG supaya transparan). Dipakai juga oleh Settings SPM.
export async function imageToDataUrl(file, maxW, maxH) {
  if (!/^image\/(png|jpeg)$/.test(file.type)) throw new Error('Please use a PNG or JPG image (transparent PNG recommended).');
  if (file.size > 1024 * 1024) throw new Error('The image is larger than 1 MB.');
  const url = URL.createObjectURL(file);
  try {
    const img = await new Promise((res, rej) => { const i = new Image(); i.onload = () => res(i); i.onerror = () => rej(new Error('Unable to read the image.')); i.src = url; });
    const k = Math.min(1, maxW / img.naturalWidth, maxH / img.naturalHeight);
    const c = document.createElement('canvas');
    c.width = Math.max(1, Math.round(img.naturalWidth * k)); c.height = Math.max(1, Math.round(img.naturalHeight * k));
    const ctx = c.getContext('2d');
    if (file.type === 'image/jpeg') { ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, c.width, c.height); }
    ctx.drawImage(img, 0, 0, c.width, c.height);
    return file.type === 'image/png' ? c.toDataURL('image/png') : c.toDataURL('image/jpeg', 0.9);
  } finally { URL.revokeObjectURL(url); }
}

export async function fetchDocBytes(storagePath) {
  const { data, error } = await supabase.storage.from(DOCS_BUCKET).download(storagePath);
  if (error) throw error;
  return new Uint8Array(await data.arrayBuffer());
}

const dataUrlBytes = (u) => {
  const m = /^data:image\/(png|jpe?g);base64,(.+)$/i.exec(String(u || ''));
  if (!m) return null;
  const bin = atob(m[2]);
  const b = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) b[i] = bin.charCodeAt(i);
  return { png: /png/i.test(m[1]), bytes: b };
};

// Cari kolom "PIHAK KEDUA," pada blok tanda tangan BAST (teks yang digambar generator) lewat pdfjs
async function findOwnerArea(bytes) {
  const m = await import('pdfjs-dist');
  const pdfjs = m.GlobalWorkerOptions ? m : m.default;
  if (!pdfjs.GlobalWorkerOptions.workerSrc) pdfjs.GlobalWorkerOptions.workerSrc = new URL('pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url).toString();
  const doc = await pdfjs.getDocument({ data: bytes.slice() }).promise;
  let hit = null;
  try {
    for (let i = 1; i <= doc.numPages; i++) {
      const page = await doc.getPage(i);
      const tc = await page.getTextContent();
      // "PIHAK KEDUA," (dengan koma) = judul kolom tanda tangan; "PIHAK KEDUA" tanpa koma = identitas di atas
      tc.items.filter((it) => String(it.str || '').trim() === 'PIHAK KEDUA,').forEach((it) => {
        hit = { pageIndex: i - 1, x: it.transform[4], y: it.transform[5], w: it.width };
      });
    }
  } finally { doc.destroy(); }
  return hit;
}

// Return PDF baru dengan tanda tangan owner di kolom PIHAK KEDUA (jumlah halaman tidak berubah)
export async function stampOwnerSignature(bytes, { sig, stamp }) {
  if (!sig) throw new Error('Upload your owner signature first.');
  const area = await findOwnerArea(bytes);
  if (!area) throw new Error('No partner signature area was found in this file. Only BAST documents generated by SPM can be signed here.');
  const { PDFDocument } = await import('pdf-lib');
  const pdf = await PDFDocument.load(bytes);
  const page = pdf.getPage(area.pageIndex);
  const cx = area.x + area.w / 2;          // judul kolom digambar rata tengah di atas kolom
  const nameY = area.y - 15.5 - 62;        // baseline nama OWNER (lihat buildBastPdf: 15,5 + SIGN_GAP 62)
  const draw = async (url, { maxW, maxH, x, bottom, opacity = 1 }) => {
    const d = dataUrlBytes(url);
    if (!d) return;
    const img = d.png ? await pdf.embedPng(d.bytes) : await pdf.embedJpg(d.bytes);
    const k = Math.min(maxW / img.width, maxH / img.height);
    page.drawImage(img, { x: x - (img.width * k) / 2, y: bottom, width: img.width * k, height: img.height * k, opacity });
  };
  if (stamp) await draw(stamp, { maxW: 50, maxH: 50, x: cx + 34, bottom: nameY + 8, opacity: 0.9 });
  await draw(sig, { maxW: 150, maxH: 46, x: cx, bottom: nameY + 10 });
  return pdf.save();
}
