-- ============================================================================
-- Payout Tracker — partners/agencies may NOT delete documents generated by SPM
-- (BAST & Notification Letters saved under a Payment ID "PAY-…" or a legacy draft "GEN-…").
-- Run AFTER 20261007_payout_partner_docs.sql, 20261007b_payout_docs_per_po.sql
-- and 20261007c_payout_docs_uploader_role.sql (20261008 is optional/independent).
--
--  • Adds RESTRICTIVE delete policies (AND-ed with the existing permissive ppd_delete /
--    ppd_obj_delete from migration b). Nothing existing is dropped or changed.
--  • SPM (spm_sumatera) keeps full delete rights.
--  • Partners/agencies keep deleting / replacing THEIR OWN uploads on PO rows
--    (Upload to PO / Invoice: "Replace all" and the delete button rely on it).
--  • On SPM-generated documents partners can only ADD a file (the "_signed-owner" BAST copy);
--    the app never offers delete there.
--  • Idempotent: each policy is created only if it does not exist yet.
-- ============================================================================

-- Table rows
do $$
begin
  if not exists (select 1 from pg_policies
                 where schemaname = 'public' and tablename = 'payout_partner_docs' and policyname = 'ppd_delete_generated_spm_only') then
    create policy ppd_delete_generated_spm_only on public.payout_partner_docs
      as restrictive for delete to authenticated
      using (
        public.payout_docs_my_role() = 'spm_sumatera'
        or coalesce(ref_id, '') not like 'PAY-%'
        and coalesce(ref_id, '') not like 'GEN-%'
      );
  end if;
end $$;

-- Storage objects: path = <segment>/<owner_key>/<ref>/<doc_type>/<file>  → ref = foldername[3]
do $$
begin
  if not exists (select 1 from pg_policies
                 where schemaname = 'storage' and tablename = 'objects' and policyname = 'ppd_obj_delete_generated_spm_only') then
    create policy ppd_obj_delete_generated_spm_only on storage.objects
      as restrictive for delete to authenticated
      using (
        bucket_id <> 'payout-partner-docs'
        or public.payout_docs_my_role() = 'spm_sumatera'
        or coalesce((storage.foldername(name))[3], '') not like 'PAY-%'
        and coalesce((storage.foldername(name))[3], '') not like 'GEN-%'
      );
  end if;
end $$;

notify pgrst, 'reload schema';
